### ISSUE TITLE
Naive Benchmarking

### ISSUE THREAD

**Issue by grahamschock** [obroadrick/imprecise#9]
We should think about how to show our algorithm is optimal.

For right now I think this means 
- Deciding what client workloads would look like
- Code to actually profile the systems performance 
- Who decides what is good performance,  the server or the client? If it's the client we have to deal with the synchronous headache of having a process for each request 🙃 
- Generations of data and visualizations
- What is optimal?

**Comment by grahamschock** [comment]
Deliverables:
- Graph similar to Yao
- Working with just 1 client (how many requests we answer within x time) 
- Looking at how many stages 
- Looking at what deadline miss rate is
- Actually measuring accuracy, determining what accuracy would be and if our workload helps with this

**Comment by kylevitale2** [comment]
> I don't really understand. Couldn't we also have an ML that will identify something correctly accidentally? @kylevitale2
